config/routes.rb
SampleApp::Application.routes.draw do
  get "matches/new"
  resources :users, :matches, :teams
  resources :notes
  resources :sessions, only: [:new, :create, :destroy]

  root 'static_pages#home'
  match '/newmatch',  to: 'matches#new',          via: 'get'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<p class='justify'>
		In its third year of existance as an FRC team (2012-2013), team 3501 had limited scouting using a google spreadsheet. This year, a student decided that the team deserved a better scouting system, both to be more competitive and to make scouting more accessible – this is the result.
		</p>
	</div>
	<div class="col-md-3"></div>
</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>

<div class="row">
	<div class="col-md-3"></div>
	<div class="col-md-6">
		<p>
		Email or talk to Logan for help.
		</p>
	</div>
	<div class="col-md-3"></div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  For help and/or questions, email/talk to Logan.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to 3501 Scouting</h1>

  <h2>
    This is the home page for the FRC team #3501 scouting system for the 2013-2014 season.
  </h2>

	<div class="row">
		<div class="col-md-3"></div>
		<div class="col-md-2">
			<%= link_to "Sign up", signup_path, class: "btn btn-large btn-primary" %>
		</div>
		<div class="col-md-2">
			<%= link_to "New match", newmatch_path, class: "btn btn-large btn-primary" %>
		</div>
		<div class="col-md-2">
			<%= link_to "Sign in", signin_path, class: "btn btn-large btn-primary" %>
		</div>
		<div class="col-md-3"></div>
	</div>
</div>